### ISSUE TITLE
Request to include credit

### ISSUE THREAD

**Issue by jrosebr1** [franckfotso/cbir_binary_code#1]
Hey there -- it appears you are using some of my code from the PyImageSearch Gurus course, namely the `ResultsMontage`, `BaseIndexer`, etc. Please feel free to use the code in your project and congrats on it; however, it is nice when you link back to the original source. Just a request.

**Comment by franckfotso** [comment]
Hi Adrian, sorry for that. Credit added on related files.

**Comment by jrosebr1** [comment]
Thanks so much! Like I said, not a big deal, but just something that caught my attention.

By the way, you've done some great projects! I was looking at your [Faster R-CNN project](https://github.com/franckfotso/faster_rcnn_logo). What is the origin of the "ROMYNY Logo 2016 " dataset? There wasn't a citation and a Google search only returned your GitHub page. Was that a dataset you created yourself?

**Comment by franckfotso** [comment]
Well, "ROMYNY Logo 2016" is just a small dataset built by myself. I have extracted it from a dataset that I am using for another research project.
Feel free to use it :)

**Comment by jrosebr1** [comment]
Thanks! I really appreciate that 😄
